name: Lighthouse
on: [push]

jobs:
  lhci:
    name: Run Lighthouse
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Run Lighthouse
      run: |
        npm install -g @lhci/cli@0.7.x
        lhci autorun
